// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Forster Weinkerwe",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Forster Weinkerwe",
            targets: ["AppModule"],
            bundleIdentifier: "de.bollernet.playgroundforsterkerwe",
            teamIdentifier: "Z6946K9NFZ",
            displayVersion: "1.0.24",
            bundleVersion: "9",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .locationWhenInUse(purposeString: "Du kannst erkennen wohin du dich in Forst bewegen musst um einen bestimmen Ausschank, einen Toilettenwagen oder Essenstände zu finden"),
                .outgoingNetworkConnections()
            ],
            appCategory: "public.app-category.food-and-drink"
        )
    ],
    dependencies: [
        .package(url: "https://Bollerd@github.com/Bollerd/SwiftHelper", "1.0.7"..<"2.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "SwiftHelperExtensions", package: "SwiftHelper")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ],
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)
